// Mocks generated by Mockito 5.1.0 from annotations
// in ride_the_weather/test/src/city_list/domain/usercases/search_city_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:ride_the_weather/src/city_list/domain/entities/city_entity.dart'
    as _i6;
import 'package:ride_the_weather/src/city_list/domain/errors/errors.dart'
    as _i5;
import 'package:ride_the_weather/src/city_list/domain/repositories/search_city_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [SearchCityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchCityRepository extends _i1.Mock
    implements _i3.SearchCityRepository {
  MockSearchCityRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.CityEntity>> getLocationData(
          String? cityName) =>
      (super.noSuchMethod(Invocation.method(#getLocationData, [cityName]),
          returnValue: Future<_i2.Either<_i5.Failure, _i6.CityEntity>>.value(
              _FakeEither_0<_i5.Failure, _i6.CityEntity>())) as _i4
          .Future<_i2.Either<_i5.Failure, _i6.CityEntity>>);
}
